name: mobilechallenge
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  rxdart: ^0.27.5

  #hash object
  equatable: ^2.0.5

  #services locator
  get_it: ^7.2.0

  #http
  http: ^0.13.5

  #dates format
  intl: ^0.17.0

  #variable enviroment
  flutter_dotenv: ^5.0.2

  #path folder
  path_provider: ^2.0.11

  #user agent
  fk_user_agent: ^2.1.0

  #other packages
  device_info_plus: ^4.0.1
  package_info_plus: ^1.4.3
  http_parser: ^4.0.1

  #internect connection
  internet_connection_checker: ^0.0.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test:
  mockito: ^5.0.15
  build_runner: ^2.1.2
  bloc_test: ^9.0.3
  mocktail: ^0.3.0
  quiver: ^3.0.1
  hive_generator: ^1.1.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/