// Mocks generated by Mockito 5.3.2 from annotations
// in mobilechallenge/test/src/domain/usecases/usecase_get_users_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mobilechallenge/src/core/http/http_request_parameters.dart'
    as _i6;
import 'package:mobilechallenge/src/core/http/http_response_data.dart' as _i2;
import 'package:mobilechallenge/src/domain/entities/user_entity.dart' as _i5;
import 'package:mobilechallenge/src/domain/repositories/user_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponseData_0<T> extends _i1.SmartFake
    implements _i2.ResponseData<T> {
  _FakeResponseData_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i3.UserRepository {
  @override
  _i4.Future<_i2.ResponseData<List<_i5.UserEntity>>> getAll(
          _i6.HttpRequestParameters? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [params],
        ),
        returnValue: _i4.Future<_i2.ResponseData<List<_i5.UserEntity>>>.value(
            _FakeResponseData_0<List<_i5.UserEntity>>(
          this,
          Invocation.method(
            #getAll,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.ResponseData<List<_i5.UserEntity>>>.value(
                _FakeResponseData_0<List<_i5.UserEntity>>(
          this,
          Invocation.method(
            #getAll,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.ResponseData<List<_i5.UserEntity>>>);
}
